### ISSUE TITLE
Request: Add a documentation tab that uses a markdown file

### ISSUE THREAD

**Issue by Aaron-Pool** [ui-storybook/sb#30]
Hey there!

First of all, I just wanted to say this project is EXCELLENT. As a developer working on an angular 1.x project, it's very difficult to find any tools like this for general component sandbox development.

One of the few things I've found that seems to be lacking from the project is a way to incorporate for freeform information-based documentation describing the general usage of a component. I think a general "documentation" tab that can be pointed to a markdown file or string would be a great feature.

**Comment by freeman14** [comment]
@Aaron-Pool Hey. Docs feature is available now. Check documentation here https://github.com/ui-storybook/sb#components-documentation. 
Also, you need to update to version `1.3.0`
