### ISSUE TITLE
Collaborate with Storybook

### ISSUE THREAD

**Issue by ndelangen** [ui-storybook/sb#32]
Hi @freeman14 This s a really cool project you're doing! 

I looked at it a month or so ago, and it looked like development had stopped, but see you've recently committed something again. Are you interested in continued development / support on this?

I'd be interested to know if maybe we can work to create the best "Interactive development & testing environment for UI" together.

You may know about this project https://github.com/storybooks/storybook (which I'm a maintainer of). It's got a very active community and is in active development. I think we have the exact same roadmap as your project.

I'd be interested to have a chat with you about possibilities to maybe start working on a single solution instead of 2. 

I think the community of UI developers could really benefit from us working together on this common goal.
Feel free to decline, no hard feelings, hope to hear from you.

♥️ - storybook team

**Comment by freeman14** [comment]
Hey @ndelangen  
This sounds interesting 
Here my facebook page https://www.facebook.com/dmitry.dubovetsky
Let's chat
